"""Add created_by_id to media table

Revision ID: bd0b3503d841
Revises: cf0cba7315c7
Create Date: 2025-11-17 10:07:40.306812

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd0b3503d841"
down_revision: Union[str, Sequence[str], None] = "cf0cba7315c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_media_created_by_id"), ["created_by_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_media_created_by",
            "users",
            ["created_by_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_constraint("fk_media_created_by", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_media_created_by_id"))
        batch_op.drop_column("created_by_id")
    # ### end Alembic commands ###
