"""empty message

Revision ID: d03c328febc1
Revises: bd0b3503d841
Create Date: 2025-11-23 04:38:56.886357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03c328febc1'
down_revision: Union[str, Sequence[str], None] = 'bd0b3503d841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('games', sa.Column('developers', sa.JSON(), nullable=True))
    op.add_column('games', sa.Column('publishers', sa.JSON(), nullable=True))
    op.drop_column('games', 'developer')
    op.drop_column('games', 'publisher')
    op.add_column('manga', sa.Column('authors', sa.JSON(), nullable=True))
    op.drop_column('manga', 'author')
    op.add_column('movies', sa.Column('directors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'directors')
    op.add_column('manga', sa.Column('author', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('manga', 'authors')
    op.add_column('games', sa.Column('publisher', sa.VARCHAR(length=255), nullable=True))
    op.add_column('games', sa.Column('developer', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('games', 'publishers')
    op.drop_column('games', 'developers')
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
