"""first commit

Revision ID: 42cfc8652fef
Revises: 
Create Date: 2025-02-11 06:01:37.783286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42cfc8652fef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('ANIME', 'GAME', 'MOVIE', 'SERIES', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('age_rating', sa.Enum('G', 'PG', 'PG13', 'R', 'NC17', name='agerating'), nullable=True),
    sa.Column('studios', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.CheckConstraint('popularity >= 0', name='check_popularity'),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='check_rating_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_index(op.f('ix_content_title'), 'content', ['title'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('animes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translated_title', sa.String(length=100), nullable=True),
    sa.Column('episodes', sa.SmallInteger(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_genre_link',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'genre_id')
    )
    op.create_table('content_tag_link',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'tag_id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('available_platforms', sa.ARRAY(sa.Enum('PC', 'PS3', 'PS4', 'PS5', 'XBOX_360', 'XBOX_ONE', 'XBOX_SERIES_X', 'NINTENDO_SWITCH', 'IOS', 'ANDROID', 'WEB', name='platforms')), nullable=False),
    sa.Column('playtime', sa.SmallInteger(), nullable=True),
    sa.Column('stores', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('duration', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_duration', sa.SmallInteger(), nullable=True),
    sa.Column('episodes', sa.SmallInteger(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_libraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.SmallInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('FINISHED', 'IN_PROGRESS', 'DROPPED', 'PLANNED', name='status'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.CheckConstraint('priority >= 0 AND priority <= 3', name='check_priority_range'),
    sa.CheckConstraint('user_rating >= 0 AND user_rating <= 10', name='check_user_rating_range'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_libraries')
    op.drop_table('series')
    op.drop_table('movies')
    op.drop_table('games')
    op.drop_table('content_tag_link')
    op.drop_table('content_genre_link')
    op.drop_table('animes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_content_title'), table_name='content')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_table('content')
    # ### end Alembic commands ###
