"""add priority to tracking

Revision ID: c23b8626b555
Revises: d8cf0ac4c544
Create Date: 2026-02-13 07:43:43.114779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23b8626b555'
down_revision: Union[str, Sequence[str], None] = 'd8cf0ac4c544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    priority_enum = sa.Enum('LOW', 'MID', 'HIGH', name='trackingpriorityenum')
    priority_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tracking', sa.Column('priority', priority_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'priority')
    sa.Enum(name='trackingpriorityenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
