"""add priority to tracking

Revision ID: c23b8626b555
Revises: d8cf0ac4c544
Create Date: 2026-02-13 07:43:43.114779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23b8626b555'
down_revision: Union[str, Sequence[str], None] = 'd8cf0ac4c544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking', sa.Column('priority', sa.Enum('LOW', 'MID', 'HIGH', name='trackingpriorityenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'priority')
    # ### end Alembic commands ###
