"""empty message

Revision ID: d8cf0ac4c544
Revises: 
Create Date: 2025-11-23 07:04:24.435279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cf0ac4c544'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'SERIES', 'ANIME', 'MANGA', 'BOOK', 'GAME', name='mediatypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('external_source', sa.String(length=50), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_created_by_id'), 'media', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_media_external_id'), 'media', ['external_id'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('age_rating', sa.Enum('G', 'PG', 'PG_13', 'R', 'R_PLUS', 'RX', 'NC_17', 'UNKNOWN', name='ageratingenum'), nullable=True),
    sa.Column('seasons', sa.Integer(), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('studios', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('AIRING', 'FINISHED', 'UPCOMING', 'CANCELLED', name='mediastatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('developers', sa.JSON(), nullable=True),
    sa.Column('publishers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('age_rating', sa.Enum('G', 'PG', 'PG_13', 'R', 'R_PLUS', 'RX', 'NC_17', 'UNKNOWN', name='ageratingenum'), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('total_volumes', sa.Integer(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('AIRING', 'FINISHED', 'UPCOMING', 'CANCELLED', name='mediastatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'SERIES', 'ANIME', 'MANGA', 'BOOK', 'GAME', name='mediatypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'tag_id', name='uq_media_tag')
    )
    op.create_index(op.f('ix_media_tags_id'), 'media_tags', ['id'], unique=False)
    op.create_index(op.f('ix_media_tags_media_id'), 'media_tags', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_tags_media_type'), 'media_tags', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_tags_tag_id'), 'media_tags', ['tag_id'], unique=False)
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('directors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('seasons', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AIRING', 'FINISHED', 'UPCOMING', 'CANCELLED', name='mediastatusenum'), nullable=True),
    sa.Column('directors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'SERIES', 'ANIME', 'MANGA', 'BOOK', 'GAME', name='mediatypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'DROPPED', 'ON_HOLD', name='trackingstatusenum'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uq_user_media')
    )
    op.create_index(op.f('ix_tracking_id'), 'tracking', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_media_id'), 'tracking', ['media_id'], unique=False)
    op.create_index(op.f('ix_tracking_media_type'), 'tracking', ['media_type'], unique=False)
    op.create_index(op.f('ix_tracking_user_id'), 'tracking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_user_id'), table_name='tracking')
    op.drop_index(op.f('ix_tracking_media_type'), table_name='tracking')
    op.drop_index(op.f('ix_tracking_media_id'), table_name='tracking')
    op.drop_index(op.f('ix_tracking_id'), table_name='tracking')
    op.drop_table('tracking')
    op.drop_table('series')
    op.drop_table('movies')
    op.drop_index(op.f('ix_media_tags_tag_id'), table_name='media_tags')
    op.drop_index(op.f('ix_media_tags_media_type'), table_name='media_tags')
    op.drop_index(op.f('ix_media_tags_media_id'), table_name='media_tags')
    op.drop_index(op.f('ix_media_tags_id'), table_name='media_tags')
    op.drop_table('media_tags')
    op.drop_table('manga')
    op.drop_table('games')
    op.drop_table('books')
    op.drop_table('anime')
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_external_id'), table_name='media')
    op.drop_index(op.f('ix_media_created_by_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
